### ISSUE TITLE
不能持久后台运行作业？

### ISSUE THREAD

**Issue by zwei61** [cq-panda/Quartz.NetUI#1]
此项目部署后添加作业不能持久后台按间隔（cron）运行作业吗？
我当前添加了一个作业，定时每半小时一次执行，如果打开着项目界面，挨着半小时会执行。但是如果关闭着项目界面，挨着半小时时，这个作业就没有继续执行。
是有什么限制吗？
我是使用IIS无托管部署的此项目，不是直接run.bat或者dotnet 运行。

**Comment by cq-panda** [comment]
linux上就没这种问题。
我们生产环境部署在windows上的，另外开了一个window服务,这个服务里面就一段代码每5分钟调用一下这个作业站点/Health/index的接口，来保证iis站点处于活动状态。
我们就是这样干的，一直也没出现过问题。你可以试试.


------------------ 原始邮件 ------------------
发件人: "zwei61"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 下午2:07
收件人: "cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Quartz.NetUI] 不能持久后台运行作业？ (#1)




此项目部署后添加作业不能持久后台按间隔（cron）运行作业吗？
 我当前添加了一个作业，定时每半小时一次执行，如果打开着项目界面，挨着半小时会执行。但是如果关闭着项目界面，挨着半小时时，这个作业就没有继续执行。
 是有什么限制吗？
 我是使用IIS无托管部署的此项目，不是直接run.bat或者dotnet 运行。

**Comment by cq-panda** [comment]
我们生产环境部署在windows上的，另外开了一个window服务,这个服务里面就一段代码每5分钟调用一下这个作业站点/health/index的接口，来保证iis站点处于活动状态。你可以试试.

**Comment by zwei61** [comment]
哦哦，部署在iis貌似是需要轮循调用让他处于活动下，我已经常识使用dotnet Quartz.NET.Web.dll，他是处于一直活动状态。只需要解决系统重启能自动开启的问题。
谢谢
