### ISSUE TITLE
拉取最新代码后，页面报这个错，

### ISSUE THREAD

**Issue by Dysheng** [cq-panda/Quartz.NetUI#7]
![image](https://user-images.githubusercontent.com/6174604/71778154-16843200-2fe5-11ea-945f-5e6a930db47b.png)

**Comment by cq-panda** [comment]
你看下是不是task-index.js没获取到呢 ------------------ 原始邮件 ------------------
发件人: "pzgit"<notifications@github.com>
发送时间: 2020年1月5日(星期天) 下午5:59
收件人: "cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Quartz.NetUI] 拉取最新代码后，页面报这个错， (#7)




 
&mdash;
