### ISSUE TITLE
大佬们，你们报过这个错误吗？

### ISSUE THREAD

**Issue by zyf-git** [cq-panda/Quartz.NetUI#9]
Object reference not set to an instance of an object.
![image](https://user-images.githubusercontent.com/49553778/72418295-8351b600-37b5-11ea-82d2-e96810a7245a.png)

**Comment by cq-panda** [comment]
可以调试下 ------------------ 原始邮件 ------------------
发件人: "zyf-git"<notifications@github.com>
发送时间: 2020年1月15日(星期三) 下午4:39
收件人: "cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9)



Object reference not set to an instance of an object.
 
 
&mdash;

**Comment by zyf-git** [comment]
同一个分组下有多个job时，实例化的时候抛出的这个异常。不是很懂这个情况。



---原始邮件---
发件人: "保长"<notifications@github.com&gt;
发送时间: 2020年1月15日(周三) 晚上10:30
收件人: "cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"zyf-git"<3103256808@qq.com&gt;;
主题: Re: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9)


可以调试下 ------------------ 原始邮件 ------------------ 
 发件人: "zyf-git"<notifications@github.com&gt; 
 发送时间: 2020年1月15日(星期三) 下午4:39 
 收件人: "cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9) 
 
 
 
 Object reference not set to an instance of an object. 
   
   
 &amp;mdash;

**Comment by zhuzhao** [comment]
一样的，出现这个问题

**Comment by zhuzhao** [comment]
public static Task<string> HttpGetAsync(string url, Dictionary<string, string> headers = null)
        {
            try
            {
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
                if (headers != null)
                {
                    foreach (var header in headers)
                        request.Headers[header.Key] = header.Value;
                }
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                {
                    Stream responseStream = response.GetResponseStream();
                    StreamReader streamReader = new StreamReader(responseStream, Encoding.UTF8);
                    return streamReader.ReadToEndAsync();
                }
            }
            catch (Exception ex)
            {
                return Task.FromResult(ex.Message);
            }
        }

**Comment by zhuzhao** [comment]
Object reference not set to an instance of an object.”

**Comment by cq-panda** [comment]
> 一样的，出现这个问题

我们这边没有出现过这种问题，能否截个配置界面的图或者将job_options.json发一份，非常感谢

**Comment by zhuzhao** [comment]
[{"TaskName":"task1","GroupName":"task1","Interval":"0/10 * * * * ? ","ApiUrl":"http://127.0.0.1:9950/Health/KeepAlive","AuthKey":"authKey","AuthValue":"123456","Describe":null,"RequestType":"get","LastRunTime":"2020-06-01T14:51:50","Status":0}]

**Comment by zhuzhao** [comment]
你好，代码我没有动过，我只是在web页面新增了一个任务，等一会就报错了。感谢！！！！














------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"风口浪尖的猪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 下午2:34
收件人:&nbsp;"cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com&gt;;
抄送:&nbsp;"zhuzhao"<zhuzhao1010@163.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9)





  
一样的，出现这个问题
  
我们这边没有出现过这种问题，能否截个配置界面的图或者将job_options.json发一份，非常感谢

**Comment by cq-panda** [comment]
> 你好，代码我没有动过，我只是在web页面新增了一个任务，等一会就报错了。感谢！！！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"风口浪尖的猪"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月1日(星期一) 下午2:34 收件人:&nbsp;"cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com&gt;; 抄送:&nbsp;"zhuzhao"<zhuzhao1010@163.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9) 一样的，出现这个问题 我们这边没有出现过这种问题，能否截个配置界面的图或者将job_options.json发一份，非常感谢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

代码刚刚已经更新过了，可以获取看看

**Comment by zhuzhao** [comment]
感谢

**Comment by zhuzhao** [comment]
今天获取了新代码，没有错误了，感谢！！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"风口浪尖的猪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 下午5:55
收件人:&nbsp;"cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com&gt;;
抄送:&nbsp;"zhuzhao"<zhuzhao1010@163.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9)





  
你好，代码我没有动过，我只是在web页面新增了一个任务，等一会就报错了。感谢！！！！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"风口浪尖的猪"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月1日(星期一) 下午2:34 收件人:&nbsp;"cq-panda/Quartz.NetUI"<Quartz.NetUI@noreply.github.com&gt;; 抄送:&nbsp;"zhuzhao"<zhuzhao1010@163.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [cq-panda/Quartz.NetUI] 大佬们，你们报过这个错误吗？ (#9) 一样的，出现这个问题 我们这边没有出现过这种问题，能否截个配置界面的图或者将job_options.json发一份，非常感谢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
代码刚刚已经更新过了，可以获取看看
